name = "Create Down To Earth"
author = "Vercte"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b4c89d2febc94ac1cef9fa3c673b30a5e9a0adec1e61f6adf31e8f1a6cbd3be"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
