name = "Create Down To Earth"
author = "Vercte"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d69fba90f2a9e9956eac6bebfb8c7a832409a062dae88e22d481236fe12f288"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
