name = "Create Down To Earth"
author = "Vercte"
version = "1.6.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f250f691e6ffa3088ba7c457e2edf7059d1a3ff967a75963b6ceec5228983b5"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
