name = "Create Down To Earth"
author = "Vercte"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d5eb69fe8f02bd433b0a9df4c990aeed2442a36acbd8fef5d9dbdc4f597e1db"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
