name = "Create Down To Earth"
author = "Vercte"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d99f1871e756e8a711d5600e6d552364d6bd1bd319ea1e7b18770077a334b88"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
