name = "Create Down To Earth"
author = "Vercte"
version = "1.6.0c"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b42fdff2f7cf577803f12ce9a608dd842063f27529f46a6545388ad1b84ec2c5"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
