name = "Create Down To Earth"
author = "Vercte"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcd79088a76e2d6af73006b729fa8dcaa395e9b638f91ea944428794c244b0b4"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
