name = "Create Down To Earth"
author = "Vercte"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3867c9a79a2aab7f087ed182045f54b4a54603985ce0c845cc86cbd81b85369c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
