name = "Create Down To Earth"
author = "Vercte"
version = "1.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1e7e248f7122fd63e3fc7e3e7b70575924dbc262dd349f1cea31bf32213ba8c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
