name = "Create Down To Earth"
author = "Vercte"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc836ad693b331a2190e6f86f2ad33119e855fa738e1dec1b315537b863c58bb"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
