name = "Create Down To Earth"
author = "Vercte"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62b4dd87a1cd73c523cea9c9af040e0eeed40ded98044816e4a8676555a3c2ab"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
