name = "Create Down To Earth"
author = "Vercte"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2282c307e4284193600ffff5554a9862c2ba38bf1a086409a041b1d459f16d9e"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
